chore: moving to go build -p 1 in order to reduce the number of falied builds
See the errors:

ERROR: failed to build: failed to solve: Unavailable: error reading from server: EOF
Cleaning up project directory and file based variables
00:50
WARNING: Failed to inspect predefined container 62d91abd7278a35fe2f90a1eec25208eafcb6b3fe729ba3418f16b04cc60a79c Get "https://10.164.0.84:2376/v1.47/containers/62d91abd7278a35fe2f90a1eec25208eafcb6b3fe729ba3418f16b04cc60a79c/json": dial tcp 10.164.0.84:2376: i/o timeout (docker_command.go:155:10s)
Using helper image:  registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v18.4.0
Using effective pull policy of [always] for container registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v18.4.0
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v18.4.0 ...
WARNING: Failed to pull image with policy "always": Post "https://10.164.0.84:2376/v1.47/images/create?fromImage=registry.gitlab.com%2Fgitlab-org%2Fgitlab-runner%2Fgitlab-runner-helper&tag=x86_64-v18.4.0": dial tcp 10.164.0.84:2376: i/o timeout (manager.go:238:10s)
ERROR: Failed to remove container 390b82a7960767707d41e03fe509faab4f8011896f6d4f25b341331050538e53
ERROR: Failed to remove container 985e4f394df33faae5beec71cb428d682b6e95d9301d0a8454966b7abb16a566
ERROR: Failed to remove container 62d91abd7278a35fe2f90a1eec25208eafcb6b3fe729ba3418f16b04cc60a79c
ERROR: Job failed (system failure): waiting for container: Post "https://10.164.0.84:2376/v1.47/containers/985e4f394df33faae5beec71cb428d682b6e95d9301d0a8454966b7abb16a566/wait?condition=not-running": dial tcp 10.164.0.84:2376: i/o timeout

https://gitlab.com/Northern.tech/Mender/integration-test-runner/-/jobs/13001359104

Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>